fix(DI-58): Adjust project panel of  deleted
choice-form/mono-apps pull request #266
Opened 2022-01-13 10:42 UTC by shqpeng

2022-01-13 12:28 UTC, nightire requested changes

2022-01-13 12:28 UTC, nightire commented on packages/data-insight/app/components/projects/project.hbs
> +    "bg-body
这一串样式名是自动格式化出来的？如果是的话那可能是 prettier 出问题了，因为它们本来应该在同一行。

2022-01-13 13:45 UTC, shqpeng commented on packages/data-insight/app/components/projects/project.hbs
> +    "bg-body
> 这一串样式名是自动格式化出来的？如果是的话那可能是 prettier 出问题了，因为它们本来应该在同一行。

我的操作中,在图1这里保存了一下变成了图2这样子,然后全选加上"
以后对不超过一行最大限制就换行的地方,会注意下的

<img src="https://user-images.githubusercontent.com/38524100/149340203-1e007399-f242-432a-bf23-9b449e9ce164.png" width=400>

<img src="https://user-images.githubusercontent.com/38524100/149340837-e41930d0-89a6-459f-b78d-4672abb8d7a5.png" width=400>

2022-01-17 02:39 UTC, nightire approved these changes

2022-01-17 02:40 UTC, merged